#!/usr/bin/env python3

import pathlib

import cairo
import gi

gi.require_version("Pango", "1.0")
gi.require_version("PangoCairo", "1.0")

from gi.repository import Pango, PangoCairo


TYPEFACE = "Liberation Mono"
ALPHA_THRESHOLD = 96
OUTPUT = pathlib.Path("kernel/src/console_font.c")

# Keep width <= 16 so one console_font_row_t can hold a row.
FONT_VARIANTS = [
    (7, 14, 8),
    (8, 16, 9),
    (9, 18, 10),
    (10, 20, 11),
    (11, 23, 12),
    (12, 25, 13),
    (13, 27, 14),
    (14, 29, 15),
    (15, 32, 16),
    (16, 34, 17),
]

# CP437 has graphic symbols in the control range that Python's codec maps to
# U+0001..U+001F instead of the visible VGA glyphs, so spell those out.
CP437_CHARS = [
    " ",
    "☺",
    "☻",
    "♥",
    "♦",
    "♣",
    "♠",
    "•",
    "◘",
    "○",
    "◙",
    "♂",
    "♀",
    "♪",
    "♫",
    "☼",
    "►",
    "◄",
    "↕",
    "‼",
    "¶",
    "§",
    "▬",
    "↨",
    "↑",
    "↓",
    "→",
    "←",
    "∟",
    "↔",
    "▲",
    "▼",
]
CP437_CHARS.extend(bytes([value]).decode("cp437") for value in range(32, 127))
CP437_CHARS.append("⌂")
CP437_CHARS.extend(bytes([value]).decode("cp437") for value in range(128, 255))
CP437_CHARS.append("\u00a0")


def render_glyph_rows(layout, cell_surface, cell_ctx, glyph, width, height):
    cell_ctx.save()
    cell_ctx.set_operator(cairo.OPERATOR_SOURCE)
    cell_ctx.set_source_rgba(0.0, 0.0, 0.0, 0.0)
    cell_ctx.paint()
    cell_ctx.restore()

    layout.set_text(glyph, -1)
    _, logical = layout.get_pixel_extents()

    x = (width - logical.width) / 2.0 - logical.x
    y = (height - logical.height) / 2.0 - logical.y

    cell_ctx.move_to(x, y)
    cell_ctx.set_source_rgba(1.0, 1.0, 1.0, 1.0)
    PangoCairo.show_layout(cell_ctx, layout)

    rows = []
    data = cell_surface.get_data()
    stride = cell_surface.get_stride()
    for y in range(height):
        row_bits = 0
        for x in range(width):
            if data[y * stride + x] > ALPHA_THRESHOLD:
                row_bits |= 1 << (width - 1 - x)
        rows.append(row_bits)
    return rows


def render_variant(width, height, point_size):
    cell_surface = cairo.ImageSurface(cairo.FORMAT_A8, width, height)
    cell_ctx = cairo.Context(cell_surface)

    font_options = cairo.FontOptions()
    font_options.set_antialias(cairo.ANTIALIAS_GRAY)
    font_options.set_hint_style(cairo.HINT_STYLE_FULL)
    font_options.set_hint_metrics(cairo.HINT_METRICS_ON)
    cell_ctx.set_font_options(font_options)

    layout = PangoCairo.create_layout(cell_ctx)
    layout.set_font_description(Pango.FontDescription(f"{TYPEFACE} {point_size}"))
    return [render_glyph_rows(layout, cell_surface, cell_ctx, glyph, width, height) for glyph in CP437_CHARS]


def main():
    max_width = max(width for width, _, _ in FONT_VARIANTS)
    max_height = max(height for _, height, _ in FONT_VARIANTS)

    lines = [
        '#include "console_font.h"',
        "",
        "/*",
        " * Generated by tools/generate_console_font.py",
        f" * Typeface: {TYPEFACE}",
        f" * Alpha threshold: {ALPHA_THRESHOLD}",
        f" * Variants: {', '.join(f'{w}x{h}@{pt}pt' for w, h, pt in FONT_VARIANTS)}",
        " */",
        "",
        f"_Static_assert(CONSOLE_FONT_MAX_WIDTH >= {max_width}, \"console font width table too small\");",
        f"_Static_assert(CONSOLE_FONT_MAX_HEIGHT >= {max_height}, \"console font height table too small\");",
        f"_Static_assert(CONSOLE_FONT_VARIANT_COUNT == {len(FONT_VARIANTS)}, \"console font variant count mismatch\");",
        "",
        "const struct console_font_variant g_console_font_variants[CONSOLE_FONT_VARIANT_COUNT] = {",
    ]

    for width, height, point_size in FONT_VARIANTS:
        glyph_rows = render_variant(width, height, point_size)
        lines.append("    {")
        lines.append(f"        .width = {width},")
        lines.append(f"        .height = {height},")
        lines.append("        .glyphs = {")
        for rows in glyph_rows:
            padded = rows + [0] * (max_height - height)
            rendered_rows = ", ".join(f"0x{row:04x}" for row in padded)
            lines.append(f"            {{{rendered_rows}}},")
        lines.append("        },")
        lines.append("    },")

    lines.append("};")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
