#!/usr/bin/env python3

import pathlib

import cairo
import gi

gi.require_version("Pango", "1.0")
gi.require_version("PangoCairo", "1.0")

from gi.repository import Pango, PangoCairo


FONT_DESCRIPTION = "Liberation Mono 13"
FONT_WIDTH = 12
FONT_HEIGHT = 25
ALPHA_THRESHOLD = 96
OUTPUT = pathlib.Path("kernel/src/console_font.c")

# CP437 has graphic symbols in the control range that Python's codec maps to
# U+0001..U+001F instead of the visible VGA glyphs, so spell those out.
CP437_CHARS = [
    " ",
    "☺",
    "☻",
    "♥",
    "♦",
    "♣",
    "♠",
    "•",
    "◘",
    "○",
    "◙",
    "♂",
    "♀",
    "♪",
    "♫",
    "☼",
    "►",
    "◄",
    "↕",
    "‼",
    "¶",
    "§",
    "▬",
    "↨",
    "↑",
    "↓",
    "→",
    "←",
    "∟",
    "↔",
    "▲",
    "▼",
]
CP437_CHARS.extend(bytes([value]).decode("cp437") for value in range(32, 127))
CP437_CHARS.append("⌂")
CP437_CHARS.extend(bytes([value]).decode("cp437") for value in range(128, 255))
CP437_CHARS.append("\u00a0")


def render_glyph_rows(layout, cell_surface, cell_ctx, glyph):
    cell_ctx.save()
    cell_ctx.set_operator(cairo.OPERATOR_SOURCE)
    cell_ctx.set_source_rgba(0.0, 0.0, 0.0, 0.0)
    cell_ctx.paint()
    cell_ctx.restore()

    layout.set_text(glyph, -1)
    _, logical = layout.get_pixel_extents()

    x = (FONT_WIDTH - logical.width) / 2.0 - logical.x
    y = (FONT_HEIGHT - logical.height) / 2.0 - logical.y

    cell_ctx.move_to(x, y)
    cell_ctx.set_source_rgba(1.0, 1.0, 1.0, 1.0)
    PangoCairo.show_layout(cell_ctx, layout)

    rows = []
    data = cell_surface.get_data()
    stride = cell_surface.get_stride()
    for y in range(FONT_HEIGHT):
        row_bits = 0
        for x in range(FONT_WIDTH):
            if data[y * stride + x] > ALPHA_THRESHOLD:
                row_bits |= 1 << (FONT_WIDTH - 1 - x)
        rows.append(row_bits)
    return rows


def main():
    cell_surface = cairo.ImageSurface(cairo.FORMAT_A8, FONT_WIDTH, FONT_HEIGHT)
    cell_ctx = cairo.Context(cell_surface)

    font_options = cairo.FontOptions()
    font_options.set_antialias(cairo.ANTIALIAS_GRAY)
    font_options.set_hint_style(cairo.HINT_STYLE_FULL)
    font_options.set_hint_metrics(cairo.HINT_METRICS_ON)
    cell_ctx.set_font_options(font_options)

    layout = PangoCairo.create_layout(cell_ctx)
    layout.set_font_description(Pango.FontDescription(FONT_DESCRIPTION))

    glyph_rows = [render_glyph_rows(layout, cell_surface, cell_ctx, glyph) for glyph in CP437_CHARS]

    lines = [
        '#include "console_font.h"',
        "",
        "/*",
        " * Generated by tools/generate_console_font.py",
        f" * Source font: {FONT_DESCRIPTION}",
        f" * Cell size: {FONT_WIDTH}x{FONT_HEIGHT}",
        f" * Alpha threshold: {ALPHA_THRESHOLD}",
        " */",
        "",
        "const console_font_row_t g_console_font[256][CONSOLE_FONT_HEIGHT] = {",
    ]

    for rows in glyph_rows:
        rendered_rows = ", ".join(f"0x{row:04x}" for row in rows)
        lines.append(f"    {{{rendered_rows}}},")

    lines.append("};")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
